export const ADD_ITEM_ACTION_IN_RESTAURANT = 'ADD_ITEM_ACTION_IN_RESTAURANT';
export const UPDATE_ITEM_ACTION_IN_RESTAURANT = 'UPDATE_ITEM_ACTION_IN_RESTAURANT';
export const DELETE_ITEM_RESTAURANT_ACTION_IN_RESTAURANT = 'DELETE_ITEM_RESTAURANT_ACTION_IN_RESTAURANT';
export const DELETE_ALL_ITEM_ACTION_IN_RESTAURANT = 'DELETE_ALL_ITEM_ACTION_IN_RESTAURANT';

export const ADD_DATA = 'ADD_DATA';
export const DELETE_ALL_DATA = 'DELETE_ALL_DATA';